### ISSUE TITLE
Uncached Bach 17 requires an init step

### ISSUE THREAD

**Issue by sormuras** [kordamp/gm#41]
If Bach 17 is to be executed in the current directory and there's no `.bach` subdirectory, the canonical way to initialize and run Bach 17 is a two-step story:

- `jshell https://bit.ly/bach-init`
- `.bach/bin/bach <ARGS>`

The latter is a short-cut for `java --module-path .bach/bin --module com.github.sormuras.bach <ARGS>`

**Comment by aalmiray** [comment]
So far `gm` assumes the project contains the appropriate markers that identify it as a particular tool bound project (settings.gradle[.kts] for Gradle, pom.xml for Maven, .jbang for jbang, and .bach for Bach). Sometimes two or more markers may be available thus `gm` picks one from its discovery list (configurable). An explicit choice can be set on the command line:
* -gg for Gradle
* -gm for Maven
* -gb for Bach
* -gj for jbang

This issue states that one can run Bach on a project that has yet to be set as such. In this case `gm` will fail to automagically detect a Bach project. What could happen is that if the `-gb` flag is explicitly given AND if the current directory is does not contain a `.bach` directory THEN the Bach init step could be invoked. However this only makes sense when invoking from the root of the project. Invoking from somewhere else within the project structure (such as `src/<moduleName>/java` would result in the `.bach` directory being placed at the wrong location; which is why I'm hesitant to let `gm` make the decision for the developer.

**Comment by sormuras** [comment]
It's totally fine requiring users to pass `-gb` in this case.

Only a few projects will lack the `.bach` directory in their root. Perhaps, those are only demo projects, like: https://github.com/sormuras/simplicissimus 

Which depend on Bach being initialized [on-the-fly](https://github.com/sormuras/simplicissimus/blob/4b88da2792fbb3b37a45c090fd0ffcde81abeb9f/.github/workflows/ci.yml#L33-L37):
```yml
      - name: 'Initialize Bach'
        run: jshell https://bit.ly/bach-init
      - name: 'Build with Bach'
        run: .bach/bin/bach --project-version ${{ env.VERSION_AND_BUILD }} --project-targets-java 9 build
```

That's where the two-step init process is required.

Most projects using Bach will bring along a `.bach` directory including their version of Bach they depend on; plus project-specific configurations. So, feel free to close this ticket.

**Comment by sormuras** [comment]
Closed due to reasoning above.
